# https://dev.classmethod.jp/articles/cloudformation-nested-ec2/

Description: WEB Server

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Value: !Ref EnvironmentName

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  ImageId:
    Description: AMI ID
    Type: String

  InstanceType:
    Description: WebServer EC2 instance type,
    Type": String,
    Default: t2.small,
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.

Resources:
  WEBInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      # SecurityGroups: !Ref WEBSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: !Ref ProtectedSubnet1
          GroupSet:
            - !GetAtt WEBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-web-1

  WEBInstance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      # SecurityGroups: !Ref WEBSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: !Ref ProtectedSubnet2
          GroupSet:
            - !GetAtt WEBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-web-2
    Metadata:
      AWS::CloudFormation::Init: 
        config: 
          commands: 
            - "yum install -y https://s3.region.amazonaws.com/amazon-ssm-region/latest/linux_amd64/amazon-ssm-agent.rpm"
            - "systemctl enable amazon-ssm-agent"
            - "systemctl start amazon-ssm-agentx"          
  
  WEBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: WEB Security Group
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-sg-web
