version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
        - composer install --working-dir=./
  pre_build:
    commands:
      - composer stan --working-dir=./
  #build: 
  #  commands: 
  #    - sample